server:
  port: 8080

spring:
  application:
    name: liar-rag
  data:
    redis:
      host: localhost
      port: 6379
      password: Pjr@18556720503

# langchain4j 相关配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: debug

