server:
  port: 8080

spring:
  application:
    name: liar-zhiliao
  data:
    redis:
      host: localhost
      port: 6379
      password: Pjr@18556720503

# langchain4j 相关配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://llm-kyz5903txm3fyz8f.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      api-key: ${QWEN_API_KEY}
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: debug
